### ISSUE TITLE
dev-java/leveldbjni cannot be built with dev-libs/leveldb::gentoo

### ISSUE THREAD

**Issue by Leo3418** [6-6-6/spark-overlay#11]
In the [build instructions](https://github.com/fusesource/leveldbjni/tree/leveldbjni-1.8#build-procedure) of `leveldbjni` given by the upstream, `leveldb` needs to be patched so some members in one of its classes are no longer `private` and `leveldbjni` can thus access them:

```patch
--- a/include/leveldb/slice.h
+++ b/include/leveldb/slice.h
@@ -77,7 +77,6 @@ class Slice {
             (memcmp(data_, x.data_, x.size_) == 0));
   }

- private:
   const char* data_;
   size_t size_;
```

Without this patch, `dev-java/leveldbjni` cannot be built from source:

```
src/leveldbjni_structs.cpp: In function 'leveldb::Slice* getNativeSliceFields(JNIEnv*, jobject, leveldb::Slice*)':
src/leveldbjni_structs.cpp:248:19: error: 'const char* leveldb::Slice::data_' is private within this context
  248 |         lpStruct->data_ = (const char*)(intptr_t)env->GetLongField(lpObject, NativeSliceFc.data_);
      |                   ^~~~~
In file included from /usr/include/leveldb/iterator.h:19,
                 from /usr/include/leveldb/db.h:12,
                 from src/leveldbjni.h:71,
                 from src/leveldbjni_structs.cpp:10:
/usr/include/leveldb/slice.h:89:15: note: declared private here
   89 |   const char* data_;
      |               ^~~~~
```

This is the main reason why the Spark overlay has a [separate copy](/6-6-6/spark-overlay/tree/master/dev-libs/leveldb) of the `dev-libs/leveldb` package, which [incorporates the patch](/6-6-6/spark-overlay/blob/e174aad276f1481aef4e25e3a99a7ce16d8faffa/dev-libs/leveldb/files/leveldb-1.20-support-leveldbjni.patch).

With the copy from this overlay (`dev-libs/leveldb::spark-overlay`) installed on the system, `dev-java/leveldbjni` can be built without the aforementioned error. But, chances are some users have already installed the copy of the package from the Gentoo repository (`dev-libs/leveldb::gentoo`) on their system before merging `dev-java/leveldbjni` (e.g. they have installed another package that depends on `leveldb`), and the `::gentoo` copy does not have the patch applied. In this case, when `dev-java/leveldbjni` is being installed, `dev-libs/leveldb::spark-overlay` will not be pulled to replace `dev-libs/leveldb::gentoo`, and the above error will occur.

Users can resolve the problem by manually replacing `dev-libs/leveldb::gentoo` with `dev-libs/leveldb::spark-overlay`:

```console
# emerge --ask --oneshot --verbose dev-libs/leveldb::spark-overlay
```

However, this issue still negatively affects the user experience of this overlay. The workaround above might not be intuitive to users, including maybe even experienced Gentoo veterans; the necessity of the workaround also prevents the most optimal goal of making any package installable with only a single command from being met.

Here are some solutions (more like workarounds still) to this issue that can be applied at the Spark overlay's end:

- Introduce the `_p` version suffix to `leveldb` ebuilds in this overlay so they always stay ahead of the ebuilds in `::gentoo`. For example, as of now, `::gentoo` has `leveldb-1.20.ebuild` and `leveldb-1.23.ebuild`, so this overlay should have `leveldb-1.20_p1.ebuild` and `leveldb-1.23_p1.ebuild`. This way, the copy from this overlay will always be installed regardless of whether the users' system already has the copy from `::gentoo`.

  Benefits:
  - Even if any ebuild in `::gentoo` receives a revision bump (e.g. `leveldb-1.23-r1.ebuild`), the ebuild in this overlay still takes precedence because suffix takes precedence over revision per Gentoo PMS, so `1.23_p1 > 1.23-r1`.
  
  Drawbacks:
  - Version suffix is a part of `PV`, which affects any usages of `PV` in the ebuilds, such as in `SRC_URI` and `S`. But this can be handled by defining a `MY_PV` variable and using it instead of `PV`.
  - When an ebuild for a newer upstream version is added to `::gentoo` (say `1.24`), it will take precedence over any existing ebuilds in this overlay (e.g. `1.23_p1`) until the new version is also added to this overlay (e.g. as `1.24_p1`). Adding the new version before it is stabilized in `::gentoo` should be good enough. Most users are expected to use the stable keyword, so they will not get the new version from `::gentoo` until it is stabilized.
  - In the unlikely event where Gentoo developers add the `_p` suffix to ebuilds in `::gentoo`, the suffix's integer part must be bumped for ebuilds in this overlay as well (e.g. `_p1` to `_p2`).

- Revision-bump `leveldb` ebuilds in this overlay and make sure they always stay ahead of the ebuilds in `::gentoo`. With this solution, this overlay should have `leveldb-1.20-r1.ebuild` and `leveldb-1.23-r1.ebuild`, which take precedence over `leveldb-1.20.ebuild` and `leveldb-1.23.ebuild` in `::gentoo`.

  Benefits:
  - `PV` is unaffected by revision bumps, so changes to the `leveldb` ebuilds will be minimal.
 
  Drawbacks:
  - When Gentoo developers make a revision bump (say from `1.23` to `1.23-r1`), the ebuilds in this overlay need to be revision-bumped too (from `1.23-r1` to `1.23-r2`).

- Display a message from ebuilds for `dev-java/leveldbjni` telling the users that they need to install `dev-libs/leveldb::spark-overlay` in case it cannot be built (e.g. `elog` in `pkg_pretend` phase).

  Benefits:
  - The required amount of work from the Spark overlay's maintainers is reduced. There is more tolerance for the delay of updates to this overlay after updates to `::gentoo`.
  
  Drawbacks:
  - This is only a means to present the solution of the issue to the users; it does not directly solve the issue, as the version of `leveldb` with the required patch applied is still not automatically installed. The best thing it might be able to do is to reduce the number of support requests from the users.
  - The users might not notice the message when an error occurs and other error messages are being flooded with it together in the package manager's standard output, so they might still not know how the issue should be fixed.

**Comment by heroxbd** [comment]
How about sending a merge request to https://github.com/google/leveldb to make the class members public?

**Comment by Leo3418** [comment]
@heroxbd Didn't get a change to come back to this issue until today. I just came up with another resolution: create a temporary copy of `slice.h` when `leveldbjni` is being built, patch that copy, and use it instead of the unpatched copy located in `/usr/include`. Do you think this is a feasible solution?

```bash
src_prepare() {
	...

	# Create a temporary patched copy of slice.h
	pushd "${JNI_SRC_DIR}" || die # JNI_SRC_DIR is referred to by one of the -I options passed to GCC
	mkdir leveldb || die
	cp "${ESYSROOT}/usr/include/leveldb/slice.h" leveldb || die
	eapply -p2 "${FILESDIR}/leveldb-1.20-support-leveldbjni.patch"
	popd || die
}
```

**Comment by heroxbd** [comment]
> @heroxbd Didn't get a change to come back to this issue until today. I just came up with another resolution: create a temporary copy of `slice.h` when `leveldbjni` is being built, patch that copy, and use it instead of the unpatched copy located in `/usr/include`. Do you think this is a feasible solution?
> 
> ```shell
> src_prepare() {
> 	...
> 
> 	# Create a temporary patched copy of slice.h
> 	pushd "${JNI_SRC_DIR}" || die # JNI_SRC_DIR is referred to by one of the -I options passed to GCC
> 	mkdir leveldb || die
> 	cp "${ESYSROOT}/usr/include/leveldb/slice.h" leveldb || die
> 	eapply -p2 "${FILESDIR}/leveldb-1.20-support-leveldbjni.patch"
> 	popd || die
> }
> ```

Good idea!  Let's go this way.
