### ISSUE TITLE
Some ebuilds fail src_test phase with 'emerge -B' and USE="binary"

### ISSUE THREAD

**Issue by Leo3418** [6-6-6/spark-overlay#12]
The `-B` option of `emerge(1)` is the short-hand for `--buildpkgonly`: it makes `emerge` *only* build binary packages for requested ebuilds without installing them to the current system. When the `-B` option is active, `emerge` will only pull in build-time dependencies listed in `BDEPEND` and `DEPEND` of the requested ebuilds.

This causes an issue for ebuilds in the Spark overlay that meet all of the following conditions:
- They have a `binary` USE flag and USE-conditional Java package dependencies based on this USE flag
- They inherit the `java-pkg-simple` eclass and use the default `java-pkg-simple_src_test` phase function for `src_test`
- They only have the `pkgdiff` test enabled in `JAVA_TESTING_FRAMEWORKS`

The `binary` USE flag causes the ebuild to install a pre-built JAR instead of compile and make a JAR from source. So, when it is enabled, none of the Java library dependencies need to exist during the build time, hence these ebuilds' `DEPEND` is often declared like this:

```bash
DEPEND="
	>=virtual/jdk-1.8:*
	!binary? (
		dev-java/foo
		dev-java/bar
	)
"
```
When `FEATURES="test"` is enabled, `emerge` will run the `src_test` phase function for those ebuilds, which is `java-pkg-simple_src_test`. That function will try to compile any test sources in the source directory (even if `USE="binary"` is enabled and none of JUnit and TestNG is in `JAVA_TESTING_FRAMEWORKS`) before it runs the `pkgdiff` test, which only relies on the JARs, has nothing to do with the source files, and does not require any compilation at all. Compilation of test sources requires a classpath containing all the test dependencies (which inherently include all other build-time dependencies), but with `USE="binary"`, those build-time dependencies have not been installed at all due to the USE-conditional dependency declaration presented above. This results in a build error:

```
# FEATURES="test" USE="binary" emerge -Bv dev-java/h2o-core
[ebuild  N    ~] dev-java/h2o-core-3.34.0.3:3.34::spark-overlay  USE="binary test -doc -source" 0 KiB

>>> Emerging (1 of 1) dev-java/h2o-core-3.34.0.3::spark-overlay
 * h2o-3.34.0.3.tar.gz BLAKE2B SHA512 size ;-) ...                       [ ok ]
 * h2o-core-3.34.0.3-bin.jar BLAKE2B SHA512 size ;-) ...                 [ ok ]
 * Using: openjdk-8
(truncated)
>>> Compiling source in /var/tmp/portage/dev-java/h2o-core-3.34.0.3/work/h2o-3-jenkins-3.34.0.3/h2o-core ...
>>> Source compiled.
>>> Test phase: dev-java/h2o-core-3.34.0.3
!!! ERROR: Package h2o-genmodel-3.34 was not found!
 * ERROR: dev-java/h2o-core-3.34.0.3::spark-overlay failed (test phase):
 *   java-config --classpath=h2o-genmodel-3.34,h2o-jaas-pam-3.34,h2o-logger-3.34,h2o-logging-impl-classic-3.34,h2o-webserver-iface-3.34,commons-io-1,commons-lang-2.1,commons-math-3,duke,gson-2.6,jama,javassist-3,jmh-core,jmh-generator-annprocess,joda-time,jtransforms-3.1 failed
 * 
 * Call stack:
 *     ebuild.sh, line  127:  Called src_test
 *   environment, line 2422:  Called java-pkg-simple_src_test
 *   environment, line  943:  Called java-pkg-simple_getclasspath
 *   environment, line  825:  Called java-pkg_getjars '--with-dependencies' 'h2o-genmodel-3.34,h2o-jaas-pam-3.34,h2o-logger-3.34,h2o-logging-impl-classic-3.34,h2o-webserver-iface-3.34,commons-io-1,commons-lang-2.1,commons-math-3,duke,gson-2.6,jama,javassist-3,jmh-core,jmh-generator-annprocess,joda-time,jtransforms-3.1'
 *   environment, line 1719:  Called die
 * The specific snippet of code:
 *       [[ $? != 0 ]] && die "java-config --classpath=${pkgs} failed";
```
```
# FEATURES="test" USE="binary" emerge -Bv dev-java/jersey-core
[ebuild  N    ~] dev-java/jersey-core-1.9-r1:1::spark-overlay  USE="binary test -doc -source" 0 KiB

>>> Emerging (1 of 1) dev-java/jersey-core-1.9-r1::spark-overlay
 * jersey-core-1.9-sources.jar BLAKE2B SHA512 size ;-) ...               [ ok ]
 * jersey-core-1.9-bin.jar BLAKE2B SHA512 size ;-) ...                   [ ok ]
 * Using: openjdk-8
(truncated)
>>> Compiling source in /var/tmp/portage/dev-java/jersey-core-1.9-r1/work ...
>>> Source compiled.
>>> Test phase: dev-java/jersey-core-1.9-r1
!!! ERROR: Package mail was not found!
 * ERROR: dev-java/jersey-core-1.9-r1::spark-overlay failed (test phase):
 *   java-config --classpath=mail,jsr311-api,jaxb-api,osgi-core-4 failed
 * 
 * Call stack:
 *     ebuild.sh, line  127:  Called src_test
 *   environment, line 2385:  Called java-pkg-simple_src_test
 *   environment, line  919:  Called java-pkg-simple_getclasspath
 *   environment, line  791:  Called java-pkg_getjars '--build-only' '--with-dependencies' 'mail,jsr311-api,jaxb-api,osgi-core-4'
 *   environment, line 1695:  Called die
 * The specific snippet of code:
 *       [[ $? != 0 ]] && die "java-config --classpath=${pkgs} failed";
```

Possible resolutions of this issue include:

- Ignore the issue because the combination of `FEATURES="test"`, `USE="binary"` and `emerge -B` is not quite meaningful, so fixing it might not be worth the effort involved. Enabling test is useful when the ebuild is being built from source, but there is little point to test against a pre-built JAR when `USE="binary"` is enabled, especially when the only test being run is `pkgdiff`, which compares the JAR that will be installed with the pre-built JAR (and the result is always a pass if the JAR being installed is exactly the pre-built one).

- Ensure the build-time dependencies are installed when the `test` USE flag is enabled, such as:
  ```bash
  CDEPEND="
  	dev-java/foo
  	dev-java/bar
  "
  
  DEPEND="
  	>=virtual/jdk-1.8:*
  	!binary? ( ${CDEPEND} )
  	test? ( ${CDEPEND} )
  "
  ```
  However, this requires much current and future work from the Spark overlay's maintainers. Not only do existing ebuilds having this issue require an update, but new Java package ebuilds automatically generated by `java-ebuilder` need to be modified in this manner too because `java-ebuilder` does not insert something like `test? ( ${CDEPEND} )` into the ebuilds it creates as of now.

- `RESTRICT="test"` if `USE="binary"`, so `src_test` will be skipped if `USE="binary"` is enabled, hence the error will never be raised:
  ```bash
  RESTRICT="binary? ( test )"
  ```
  However, same as the previous resolution, this line is to be added to all affected current and **new** ebuilds, so it shares the similar issue.

- Modify `java-pkg-simple_src_test` so if `pkgdiff` is the only test enabled in `JAVA_TESTING_FRAMEWORKS`, then no source is compiled at all, thus the classpath does not need to be computed in `src_test`. The `kotlin-utils` eclass in this overlay already [implements such behavior](https://github.com/6-6-6/spark-overlay/blob/e174aad276f1481aef4e25e3a99a7ce16d8faffa/eclass/kotlin-utils.eclass#L623), so it is feasible. However, this change needs to be submitted to the Gentoo repository because it is where the `java-pkg-simple` eclass resides.

**Comment by 6-6-6** [comment]
I would say ignoring the issue seems fine :)
