### ISSUE TITLE
dev-java/jaxb-impl-2.2.6-r2: missing property file

### ISSUE THREAD

**Issue by efferre79** [6-6-6/spark-overlay#25]
the current implementation is missing the file `META-INF/services/javax.xml.bind.JAXBContext`, when used with recent jvm versions (I tried with 17 but I guess also 11 or 21), this is the typical error that pops out:

```
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:131)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:318)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:478)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:435)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:336)
```

**Comment by 6-6-6** [comment]
https://github.com/6-6-6/spark-overlay/blob/1666e77bcd485cb4af374d0ee2ca796eb176397f/eclass/java-pkg-maven.eclass#L65-L67

Actually `META-INF` gets removed during `src_unpack`phase. Probably we need to preserve something from it.
Here is a question:
 - should `META-INF/services` be generated during `src_compile`
 - or be copied from  `META-INF` (I suppose it should be this one: [source](https://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html))

Do you have any suggestions?

**Comment by efferre79** [comment]
> Do you have any suggestions?

I think the way you implemented looks fine

**Comment by 6-6-6** [comment]
Ok, let's merge it and see how it will affect other things
